spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/food_delivery
    username: root
    password: MYSQL
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  mail:
    host: smtp.gmail.com
    port: 587
    username: myfoodrestaurant85@gmail.com
    password: bmzlveqlqqjmgrmk
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
mapstruct:
  componentModel: spring
jwt:
  privateKey: mPWci1zOs88FnSFd2bTkspWuz2OmBtYxqtJ/YZPfu2s=

fileUpload:
  rootPath: C:\WorkSpace\JavaBackend\Food_Order\assets\img\products

cloudinary:
  cloudName: dw9bbrnke
  apiKey: 639987295942778
  apiSecret: g9AIU2wXL2JtYavmHKukq0SgNTg